eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

# by default is false ( cloud.discovery/locator/enabled )
# fetch data from the discovery
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id : students
          uri: http://localhost:8990
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8985
          predicates:
            - Path=/api/v1/schools/**


