eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8985

spring:
  application:
    name: schools
  datasource:
    url: jdbc:postgresql://localhost:5433/schools
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#application:
#  config:
#    students-url: http://localhost:8990/api/v1/students